### PR TITLE
 Embedded media support

### PR DESCRIPTION
**Pull request by fnc**
New feature as requested in issue #16.

Server: 

- new operation for Open graph data scraping.

Web:

- new react component for embedding media.

### CODE REVIEW

**Comment by pomber** [comment]
Awesome!  
Some comments:  
- Can you make the videos to not autoplay?
- The username is dropping to below the avatar:
image

**Comment by fnc** [comment]
Sure, i will check this

**Comment by fnc** [comment]
Youtube videos were working fine, i fixed twitter videos.

**Comment by pomber** [comment]
Looks great! Two more requests:  
- Could you add more padding between the media and the text?
- Can you check why is this showing when entering from an url like http://localhost:3000/realdonaldtrump?
```
warning.js:36 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the EmbeddedMedia component.
printWarning @ warning.js:36
warning @ warning.js:60
getInternalInstanceReadyForUpdate @ ReactUpdateQueue.js:48
enqueueSetState @ ReactUpdateQueue.js:200
ReactComponent.setState @ ReactComponent.js:63
EmbeddedMedia._this.handleError @ EmbeddedMedia.js:30
```

**Pull request merged**
